# This script imports a CSV file containing pairs of Azure DevOps work item IDs. 
# For each pair, it creates a 'related' relationship between the two work items. 
# It skips any pairs where either the source ID or the target ID is '#N/A'. 
# The script logs all its activity to a specified log file.
# *** 🤖 Summary generated by GitHub Copilot 🤖 ***

$CsvFile = 'C:\Users\<...>\path\to\CSV.csv'
$Logfile = 'C:\Users\<...>\Downloads\wi-links-' + $(Get-Date -Format yyyy-MM-dd_HH-mm-ss) + '.log'
$DevOpsOrg = 'https://dev.azure.com/contoso'
$WorkItemRelation = 'related'
$env:AZURE_DEVOPS_EXT_PAT = '...' # Required scope: "Work Items > Read & Write"

Start-Transcript -Path $Logfile
Write-Host "Importing file $($CsvFile)"
Import-CSV $CsvFile -Delimiter ";" | ForEach-Object { 
    $SourceId = $_.'source'
    $TargetId = $_.'target'

    if ($SourceId -eq '#N/A') {
        Write-Host "Empty source ID, skipping work item $($TargetId)"
    }
    elseif ($TargetId -eq '#N/A') {
        Write-Host "Empty target ID, skipping work item $($SourceId)"
    }
    else {
        Write-Host "Linking work item $($SourceId) to $($TargetId)"

        az boards work-item relation add --id $SourceId `
                                         --relation-type $WorkItemRelation `
                                         --org $DevOpsOrg `
                                         --target-id $TargetId `
                                         --output none
    }

}

Stop-Transcript
